opendistro_security:
  auth:
    type: openid
  openid:
    connect_url: http://0.0.0.0:8080/auth/realms/lagoon/.well-known/openid-configuration
    client_id: lagoon-opendistro-security
    client_secret: 89103750-d214-4a4b-bfd9-d54f35fec968
    base_redirect_url: http://0.0.0.0:5601
    scope: "profile email"
  cookie:
    password: moob1ahthuV0laing9Hequo8gie2ath6
    secure: 'false'
  multitenancy:
    enabled: true
    tenants:
      enable_global: true
      enable_private: false